import 'package:flutter/material.dart';

class IconHelper {
  static final Map<String, IconData> iconList = {
    'home': Icons.home,
    'shopping_cart': Icons.shopping_cart,
    'restaurant': Icons.restaurant,
    'local_gas_station': Icons.local_gas_station,
    'phone_android': Icons.phone_android,
    'wifi': Icons.wifi,
    'tv': Icons.tv,
    'school': Icons.school,
    'work': Icons.work,
    'card_giftcard': Icons.card_giftcard,
    'favorite': Icons.favorite,
    'health_and_safety': Icons.health_and_safety,
    'pets': Icons.pets,
    'sports_soccer': Icons.sports_soccer,
    'directions_car': Icons.directions_car,
    'coffee': Icons.coffee,
    'fastfood': Icons.fastfood,
    'local_dining': Icons.local_dining,
    'electrical_services': Icons.electrical_services,
    'lightbulb': Icons.lightbulb,
    'airplanemode_active': Icons.airplanemode_active,
    'beach_access': Icons.beach_access,
    'book': Icons.book,
    'child_care': Icons.child_care,
    'cleaning_services': Icons.cleaning_services,
    'computer': Icons.computer,
    'directions_bus': Icons.directions_bus,
    'fitness_center': Icons.fitness_center,
    'local_hospital': Icons.local_hospital,
    'local_mall': Icons.local_mall,
    'money': Icons.money,
    'music_note': Icons.music_note,
    'savings': Icons.savings,
    'shopping_bag': Icons.shopping_bag,
    'theaters': Icons.theaters,
    'train': Icons.train,
    'credit_card': Icons.credit_card,
    'attach_money': Icons.attach_money,
    'wallet': Icons.wallet,
    'receipt': Icons.receipt,
  };
}
