// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrSb6qZP7xtxSbLXKyYESEDkvQw-dfzbE',
    appId: '1:208449690786:web:fc90c41e78c4f5c2ab4bfb',
    messagingSenderId: '208449690786',
    projectId: 'tu-billetera-b62b5',
    authDomain: 'tu-billetera-b62b5.firebaseapp.com',
    storageBucket: 'tu-billetera-b62b5.firebasestorage.app',
    measurementId: 'G-1EVCRSPY1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHwtj8wFeadaaaYGO6VY-B8AK_NB1FpG4',
    appId: '1:208449690786:android:6c4e848ef1681707ab4bfb',
    messagingSenderId: '208449690786',
    projectId: 'tu-billetera-b62b5',
    storageBucket: 'tu-billetera-b62b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiIDRXr2MsJ9sbQNexnNZE6UfmvZDCCxs',
    appId: '1:208449690786:ios:5541f035354e1d35ab4bfb',
    messagingSenderId: '208449690786',
    projectId: 'tu-billetera-b62b5',
    storageBucket: 'tu-billetera-b62b5.firebasestorage.app',
    iosBundleId: 'com.example.tubilletera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiIDRXr2MsJ9sbQNexnNZE6UfmvZDCCxs',
    appId: '1:208449690786:ios:5541f035354e1d35ab4bfb',
    messagingSenderId: '208449690786',
    projectId: 'tu-billetera-b62b5',
    storageBucket: 'tu-billetera-b62b5.firebasestorage.app',
    iosBundleId: 'com.example.tubilletera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrSb6qZP7xtxSbLXKyYESEDkvQw-dfzbE',
    appId: '1:208449690786:web:3656d3dcea148d0bab4bfb',
    messagingSenderId: '208449690786',
    projectId: 'tu-billetera-b62b5',
    authDomain: 'tu-billetera-b62b5.firebaseapp.com',
    storageBucket: 'tu-billetera-b62b5.firebasestorage.app',
    measurementId: 'G-GFE8MTK7EX',
  );
}
